---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-crds
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: openstack-k0s-cilium-istio-kratos
  path: infrastructure/istio-crds
  dependsOn:
    - name: cert-manager
    - name: cloud-controller-manager
