---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: "1.21.2"
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    defaultRevision: default
